name: ESLint

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Display context information for debugging
      - name: Display Context Info
        run: |
          echo "🎉 The job was triggered by a ${{ github.event_name }} event."
          echo "🐧 Running on ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 Branch: ${{ github.ref }} | Repository: ${{ github.repository }}"

      # Check out repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Only fetch the latest commit to reduce build time

      # Set up Node.js environment
      - name: Set Up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Cache npm dependencies to speed up future builds
      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        working-directory: backend/server
        run: npm ci

      # Compile TypeScript
      - name: Compile TypeScript
        working-directory: backend/server
        run: npx tsc

      # Check for ESLint errors
      - name: Run ESLint
        working-directory: backend/server
        run: npx eslint . --ext .ts,.tsx

      # Final status message
      - name: ESLint Complete
        run: echo "✅ ESLint testing completed successfully!"
