name: Continuous Integration

on:
  pull_request:
    branches: [dev]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code Backend
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          working_directory: backend/
          prettier_options: --write **/*.{ts}
          only_changed: True
          same_commit: True

      - name: Prettify code Frontend
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          working_directory: frontend/
          prettier_options: --write **/*.{js,jsx}
          only_changed: True
          same_commit: True
