name: Commit Message Checker

on:
    push:
        branches:
            - main

jobs:
    run-terraform_test:
        runs-on: ubuntu-latest

        steps:
            - name: HashiCorp - Setup Terraform
              uses: hashicorp/setup-terraform@v3.1.2
            - name: Init and plan
              working-directory: terraform/state
              run:
