name: Commit Message Checker

on:
    push:
        branches:
            - dev

jobs:
    run-terraform_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: HashiCorp - Setup Terraform
              uses: hashicorp/setup-terraform@v3.1.2
            - name: Init and plan
              working-directory: terraform/state
              env:
                  AWS_SECRET_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  AWS_REGION: ${{secrets.AWS_REGION}}
              run: |
                  terraform init
                  terraform plan

            - name: Apply
              working-directory: terraform/state
              env:
                  AWS_SECRET_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  AWS_REGION: ${{secrets.AWS_REGION}}
              run: |
                  terraform apply -auto-approve
